/**
 * TUI Compiler - Code Generator
 *
 * Generates TypeScript code from the analyzed AST.
 * Clean output, source maps ready.
 */

import type { TuiFile } from '../parse/ast'
import {
  createImportCollector,
  generateImports,
  type ImportCollector,
} from '../transform/imports'
import {
  analyzeScript,
  generatePropsInterface,
  generatePropsDestructure,
  type ScriptAnalysis,
} from '../transform/script'
import { transformTemplate, createContext } from '../transform/template'

// =============================================================================
// COMPILE OPTIONS
// =============================================================================

export interface CompileOptions {
  /** Source filename for error messages */
  filename?: string
  /** Generate source maps */
  sourcemap?: boolean
  /** Development mode (extra checks) */
  dev?: boolean
  /** Component name (derived from filename) */
  name?: string
}

// =============================================================================
// COMPILE RESULT
// =============================================================================

export interface CompileResult {
  /** Generated TypeScript code */
  code: string
  /** Source map (if requested) */
  map?: string
  /** Warnings */
  warnings: string[]
  /** Detected imports */
  imports: {
    signals: string[]
    tui: string[]
    components: [string, string][]
  }
}

// =============================================================================
// COMPILE
// =============================================================================

export function compile(source: string, options: CompileOptions = {}): CompileResult {
  const { parse } = require('../parse')
  const filename = options.filename ?? 'Component.tui'
  const componentName = options.name ?? deriveComponentName(filename)

  // Parse
  const ast: TuiFile = parse(source, filename)

  // Create import collector
  const imports = createImportCollector()

  // Analyze script
  const script = analyzeScript(ast.script, imports)

  // Transform template
  const ctx = createContext(imports)
  const templateCode = transformTemplate(ast.template, ctx)

  // Generate final code
  const code = generateCode(componentName, script, templateCode, imports, options)

  return {
    code,
    warnings: [],
    imports: {
      signals: Array.from(imports.signals),
      tui: Array.from(imports.tui),
      components: Array.from(imports.components.entries()),
    },
  }
}

// =============================================================================
// CODE GENERATION
// =============================================================================

function generateCode(
  name: string,
  script: ScriptAnalysis,
  templateCode: string,
  imports: ImportCollector,
  options: CompileOptions
): string {
  const lines: string[] = []

  // Header comment
  lines.push(`/**`)
  lines.push(` * Generated by TUI Compiler`)
  lines.push(` * Source: ${options.filename ?? 'unknown'}`)
  lines.push(` * Do not edit manually`)
  lines.push(` */`)
  lines.push('')

  // Auto imports
  const autoImports = generateImports(imports)
  if (autoImports) {
    lines.push(autoImports)
  }

  // User imports (preserved)
  if (script.userImports.length > 0) {
    lines.push(script.userImports.join('\n'))
    lines.push('')
  }

  // Props interface (if component has props)
  if (script.exports.length > 0) {
    lines.push(generatePropsInterface(script.exports))
    lines.push('')
  }

  // Component function
  if (script.exports.length > 0) {
    lines.push(`export default function ${name}(props: Props) {`)
    lines.push(`  ${generatePropsDestructure(script.exports)}`)
  } else {
    lines.push(`export default function ${name}() {`)
  }

  // Script body
  if (script.body.trim()) {
    // Indent the body
    const indentedBody = script.body
      .split('\n')
      .map(line => (line.trim() ? `  ${line}` : line))
      .join('\n')
    lines.push(indentedBody)
  }

  // Template (render function)
  lines.push('')
  lines.push('  // Template')
  if (templateCode.trim()) {
    const indentedTemplate = templateCode
      .split('\n')
      .map(line => (line.trim() ? `  ${line}` : line))
      .join('\n')
    lines.push(indentedTemplate)
  }

  lines.push('}')

  return lines.join('\n')
}

// =============================================================================
// HELPERS
// =============================================================================

function deriveComponentName(filename: string): string {
  // Extract name from path
  const base = filename.split('/').pop() ?? filename
  // Remove extension
  const name = base.replace(/\.tui$/, '')
  // PascalCase
  return name
    .split(/[-_]/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}
